{
 "title": "Rainguage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  loop_cnt\nFROM telemetry\nWHERE\n  $__timeFilter(ts) AND\n  corrupt = 'false'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "rx/tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  lora_tx_bytes\nFROM telemetry\nWHERE\n  $__timeFilter(ts)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "vbat (5m average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,5m),\n  avg(vbat) AS \"vbat\"\nFROM telemetry\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}