FROM grafana/grafana:7.1.1
COPY provisioning/datasources/*  /etc/grafana/provisioning/datasources/
COPY provisioning/dashboards/* /etc/grafana/provisioning/dashboards/
COPY dashboards/* /etc/grafana/dashboards/